#pragma once

#include "version.hpp"

#ifndef MESH_CORE_ADDR_DEFAULT
#define MESH_CORE_ADDR_DEFAULT 0x00
#endif

#ifndef MESH_CORE_ADDR_BROADCAST
#define MESH_CORE_ADDR_BROADCAST 0xFF
#endif

#ifndef MESH_CORE_DELAY_MS_MIN
#define MESH_CORE_DELAY_MS_MIN 100
#endif

#ifndef MESH_CORE_DELAY_MS_MAX
#define MESH_CORE_DELAY_MS_MAX 300
#endif

#ifndef MESH_CORE_TTL_DEFAULT
#define MESH_CORE_TTL_DEFAULT 5
#endif

#ifndef MESH_CORE_LRU_RECORD_SIZE
#define MESH_CORE_LRU_RECORD_SIZE 32
#endif
