#pragma once

#include "version.hpp"

#ifndef MESH_CORE_DELAY_MS_MIN
#define MESH_CORE_DELAY_MS_MIN 100
#endif

#ifndef MESH_CORE_DELAY_MS_MAX
#define MESH_CORE_DELAY_MS_MAX 300
#endif

#ifndef MESH_CORE_TTL_DEFAULT
#define MESH_CORE_TTL_DEFAULT 10
#endif

#ifndef MESH_CORE_LRU_RECORD_SIZE
#define MESH_CORE_LRU_RECORD_SIZE 32
#endif

#ifndef MESH_CORE_ROUTE_EXPIRED_MS
#define MESH_CORE_ROUTE_EXPIRED_MS (30 * 1000)
#endif

#ifndef MESH_CORE_ROUTE_INTERVAL_MS
#define MESH_CORE_ROUTE_INTERVAL_MS (10 * 1000)
#endif
